version: '3'
services:
  api-db:
    image: postgres:alpine3.14
    container_name: blog-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres